[package]
name = "dbus-qs-example"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
zbus = { version = "5.5.0", features = ["tokio"] }
